create table
  public.smoothies (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    title text null,
    method text null,
    rating bigint null,
    constraint smoothies_pkey primary key (id)
  ) tablespace pg_default;

insert into
  smoothies (title, method, rating)
values
  (
    'Tropical Dragon Delight',
    'Ingredients: Dragon fruit, mango, pineapple, coconut water, and a squeeze of lime. Description: Blend the vibrant dragon fruit with sweet mango and tangy pineapple. Add a splash of coconut water and a squeeze of lime to enhance the tropical flavor.',
    floor(random() * 10) + 1
  ),
  (
    'Passionfruit Paradise',
    'Ingredients: Passionfruit, banana, orange juice, Greek yogurt, and honey. Description: Combine the tart passionfruit with creamy banana and fresh orange juice. Add Greek yogurt for smoothness and a drizzle of honey for natural sweetness.',
    floor(random() * 10) + 1
  ),
  (
    'Berry Kiwi Fusion',
    'Ingredients: Strawberries, blueberries, kiwi, almond milk, and chia seeds. Description: Blend ripe strawberries and blueberries with tangy kiwi. Add almond milk for a creamy texture and a spoonful of chia seeds for added nutrition.',
    floor(random() * 10) + 1
  ),
  (
    'Mango Turmeric Bliss',
    'Ingredients: Mango, banana, turmeric, coconut milk, and a pinch of black pepper. Description: Blend juicy mango with creamy banana and a dash of turmeric for its health benefits. Add coconut milk for richness and a pinch of black pepper to enhance the turmeric''s properties.',
    floor(random() * 10) + 1
  ),
  (
    'Coconut Pineapple Colada',
    'Ingredients: Pineapple, coconut cream, banana, coconut water, and a splash of vanilla extract. Description: Combine fresh pineapple with rich coconut cream and banana. Add coconut water for hydration and a hint of vanilla for extra flavor.',
    floor(random() * 10) + 1
  ),
  (
    'Papaya Ginger Zing',
    'Ingredients: Papaya, ginger, carrot juice, lime juice, and a touch of honey. Description: Blend sweet papaya with a zing of fresh ginger and vibrant carrot juice. Add a splash of lime juice and a touch of honey to balance the flavors.',
    floor(random() * 10) + 1
  ),
  (
    'Acai Berry Burst',
    'Ingredients: Acai berries, blueberries, banana, coconut water, and a drizzle of agave syrup. Description: Mix antioxidant-rich acai berries with blueberries and banana. Add coconut water for a smooth consistency and a drizzle of agave syrup for sweetness.',
    floor(random() * 10) + 1
  ),
  (
    'Exotic Guava Breeze',
    'Ingredients: Guava, pineapple, coconut milk, lime juice, and a handful of spinach. Description: Blend tropical guava with pineapple and creamy coconut milk. Add a splash of lime juice and a handful of spinach for a nutrient boost.',
    floor(random() * 10) + 1
  ),
  (
    'Pomegranate Power Punch',
    'Ingredients: Pomegranate seeds, strawberries, Greek yogurt, honey, and a dash of lemon juice. Description: Combine juicy pomegranate seeds with strawberries and Greek yogurt. Add a drizzle of honey for sweetness and a dash of lemon juice for a refreshing kick.',
    floor(random() * 10) + 1
  ),
  (
    'Lychee Lavender Dream',
    'Ingredients: Lychee, blueberries, lavender-infused honey, almond milk, and a few ice cubes. Description: Blend delicate lychee with blueberries and a touch of lavender-infused honey. Add almond milk for a creamy base and a few ice cubes for a chilled treat.',
    floor(random() * 10) + 1
  );